FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app
COPY .. .
RUN dotnet publish FoodOrdering.Api/FoodOrdering.Api.csproj -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY
